// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: create_entity.sql

package sqlc

import (
	"context"
)

const CreateEntity = `-- name: CreateEntity :one
INSERT INTO entities (field1, field2)
VALUES ($1, $2)
RETURNING id, field1, field2
`

type CreateEntityParams struct {
	Field1 string
	Field2 int32
}

func (q *Queries) CreateEntity(ctx context.Context, arg CreateEntityParams) (Entity, error) {
	row := q.db.QueryRow(ctx, CreateEntity, arg.Field1, arg.Field2)
	var i Entity
	err := row.Scan(&i.ID, &i.Field1, &i.Field2)
	return i, err
}
