// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_entity.sql

package sqlc

import (
	"context"
)

const GetEntity = `-- name: GetEntity :one
SELECT id, field1, field2
FROM entities
WHERE id = $1
`

func (q *Queries) GetEntity(ctx context.Context, id int64) (Entity, error) {
	row := q.db.QueryRow(ctx, GetEntity, id)
	var i Entity
	err := row.Scan(&i.ID, &i.Field1, &i.Field2)
	return i, err
}
