// Code generated by MockGen. DO NOT EDIT.
// Source: internal/services/embedding.go
//
// Generated by this command:
//
//	mockgen -source=internal/services/embedding.go -destination=internal/services/mocks/embedding_mock.go -package=mocks EmbeddingGateway
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	embeddings "github.com/fr33dman/go-template/internal/clients/embeddings"
	core "github.com/fr33dman/go-template/internal/core"
	gomock "go.uber.org/mock/gomock"
)

// MockEmbeddingGateway is a mock of EmbeddingGateway interface.
type MockEmbeddingGateway struct {
	ctrl     *gomock.Controller
	recorder *MockEmbeddingGatewayMockRecorder
	isgomock struct{}
}

// MockEmbeddingGatewayMockRecorder is the mock recorder for MockEmbeddingGateway.
type MockEmbeddingGatewayMockRecorder struct {
	mock *MockEmbeddingGateway
}

// NewMockEmbeddingGateway creates a new mock instance.
func NewMockEmbeddingGateway(ctrl *gomock.Controller) *MockEmbeddingGateway {
	mock := &MockEmbeddingGateway{ctrl: ctrl}
	mock.recorder = &MockEmbeddingGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmbeddingGateway) EXPECT() *MockEmbeddingGatewayMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockEmbeddingGateway) Generate(ctx context.Context, req embeddings.GenerateRequest) (embeddings.Generated, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate", ctx, req)
	ret0, _ := ret[0].(embeddings.Generated)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Generate indicates an expected call of Generate.
func (mr *MockEmbeddingGatewayMockRecorder) Generate(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockEmbeddingGateway)(nil).Generate), ctx, req)
}

// Models mocks base method.
func (m *MockEmbeddingGateway) Models(ctx context.Context) ([]core.Model, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Models", ctx)
	ret0, _ := ret[0].([]core.Model)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Models indicates an expected call of Models.
func (mr *MockEmbeddingGatewayMockRecorder) Models(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Models", reflect.TypeOf((*MockEmbeddingGateway)(nil).Models), ctx)
}
